# Generated by Django 2.2.12 on 2021-05-05 18:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ambig1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig9',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk9',
        ),
        migrations.AlterField(
            model_name='player',
            name='like',
            field=otree.db.models.StringField(choices=[('Not clear at all', 'Not clear at all'), ('Not clear', 'Not clear'), ('Clear', 'Clear'), ('Clear', 'Clear'), ('Very clear', 'Very clear')], max_length=10000, null=True),
        ),
    ]
