# Generated by Django 2.2.12 on 2021-05-05 18:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part7', '0002_auto_20210505_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='like',
            field=otree.db.models.StringField(choices=[('Strongly disagree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=10000, null=True),
        ),
    ]
