# Generated by Django 2.2.12 on 2021-05-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part7', '0003_auto_20210505_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff_slider',
        ),
    ]
