# Generated by Django 2.2.12 on 2021-09-21 17:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part7', '0004_remove_player_payoff_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enjoy',
            field=otree.db.models.StringField(choices=[('Strongly disagree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=10000, null=True),
        ),
    ]
