# Generated by Django 2.2.12 on 2022-02-22 18:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskAmb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ambig',
            field=otree.db.models.PositiveIntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, ''], [10, ''], [11, ''], [12, ''], [13, ''], [14, ''], [15, ''], [16, ''], [17, ''], [18, ''], [19, '']], null=True),
        ),
    ]
