# Generated by Django 2.2.12 on 2022-02-24 18:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='highest_bid',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='highest_bidder',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
