# Generated by Django 2.2.12 on 2022-02-24 18:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderTask', '0002_auto_20220224_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_id',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
