# Generated by Django 2.2.12 on 2022-02-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderTask', '0003_player_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_id',
        ),
    ]
