# Generated by Django 2.2.12 on 2022-03-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderTask', '0004_remove_player_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='group',
            name='highest_bidder',
        ),
    ]
