# Generated by Django 2.2.12 on 2021-09-21 19:51

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part4_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Part4_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part4_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Part4_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('bin1_mine', otree.db.models.IntegerField(null=True)),
                ('bin2_mine', otree.db.models.IntegerField(null=True)),
                ('bin3_mine', otree.db.models.IntegerField(null=True)),
                ('bin4_mine', otree.db.models.IntegerField(null=True)),
                ('bin5_mine', otree.db.models.IntegerField(null=True)),
                ('bin6_mine', otree.db.models.IntegerField(null=True)),
                ('bin7_mine', otree.db.models.IntegerField(null=True)),
                ('bin8_mine', otree.db.models.IntegerField(null=True)),
                ('bin9_mine', otree.db.models.IntegerField(null=True)),
                ('bin10_mine', otree.db.models.IntegerField(null=True)),
                ('bin1_teammate', otree.db.models.IntegerField(null=True)),
                ('bin2_teammate', otree.db.models.IntegerField(null=True)),
                ('bin3_teammate', otree.db.models.IntegerField(null=True)),
                ('bin4_teammate', otree.db.models.IntegerField(null=True)),
                ('bin5_teammate', otree.db.models.IntegerField(null=True)),
                ('bin6_teammate', otree.db.models.IntegerField(null=True)),
                ('bin7_teammate', otree.db.models.IntegerField(null=True)),
                ('bin8_teammate', otree.db.models.IntegerField(null=True)),
                ('bin9_teammate', otree.db.models.IntegerField(null=True)),
                ('bin10_teammate', otree.db.models.IntegerField(null=True)),
                ('fundamental', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Part4.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part4_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part4_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Part4.Subsession')),
            ],
            options={
                'db_table': 'Part4_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Part4.Subsession'),
        ),
    ]
