# Generated by Django 2.2.12 on 2021-05-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part4', '0002_auto_20210504_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='part2_cq1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin10_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin10_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin1_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin1_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin2_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin2_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin3_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin3_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin4_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin4_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin5_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin5_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin6_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin6_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin7_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin7_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin8_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin8_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin9_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq2_bin9_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part2_cq3',
        ),
    ]
