# Generated by Django 2.2.12 on 2021-05-08 23:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part4', '0003_auto_20210504_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fundamental',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
