# Generated by Django 2.2.12 on 2022-04-02 04:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bDrawTrueState', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_percentile',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
