# Generated by Django 2.2.12 on 2022-04-02 15:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bDrawTrueState', '0002_player_my_percentile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_percentile',
        ),
        migrations.RemoveField(
            model_name='player',
            name='own_prod',
        ),
        migrations.AddField(
            model_name='player',
            name='my_prod',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
