# Generated by Django 2.2.12 on 2022-04-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bDrawTrueState', '0003_auto_20220402_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_prod',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teammate_prod',
        ),
    ]
