# Generated by Django 2.2.12 on 2022-04-06 00:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bDrawTrueState', '0004_auto_20220402_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_prod',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='teammate_prod',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
