# Generated by Django 2.2.12 on 2022-04-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bDrawTrueState', '0005_auto_20220405_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_prod',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teammate_prod',
        ),
    ]
