# Generated by Django 2.2.12 on 2022-04-02 04:57

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cworkallocationtask_group', to='otree.Session')),
            ],
            options={
                'db_table': 'cWorkAllocationTask_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cworkallocationtask_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'cWorkAllocationTask_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('guess_mine', otree.db.models.IntegerField(null=True)),
                ('guess_teammate', otree.db.models.IntegerField(null=True)),
                ('draw_urn1', otree.db.models.IntegerField(null=True)),
                ('draw_urn2', otree.db.models.IntegerField(null=True)),
                ('team_prod', otree.db.models.FloatField(null=True)),
                ('lucky_num', otree.db.models.FloatField(null=True)),
                ('points', otree.db.models.FloatField(null=True)),
                ('check_DecisionSlider', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('check_GuessInput', otree.db.models.BooleanField(blank=True, choices=[[True, 'Confirm']], null=True)),
                ('own_ability', otree.db.models.FloatField(null=True)),
                ('teammate_ability', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cWorkAllocationTask.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cworkallocationtask_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cworkallocationtask_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cWorkAllocationTask.Subsession')),
            ],
            options={
                'db_table': 'cWorkAllocationTask_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cWorkAllocationTask.Subsession'),
        ),
    ]
