# Generated by Django 2.2.12 on 2022-04-02 16:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cWorkAllocationTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_prod',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='teammate_prod',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
