# Generated by Django 2.2.12 on 2022-04-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cWorkAllocationTask', '0002_auto_20220402_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='own_ability',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teammate_ability',
        ),
    ]
