# Generated by Django 2.2.12 on 2022-02-22 22:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('UrnBall_T1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pointsPerG_urn1',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
