# Generated by Django 2.2.12 on 2022-03-27 02:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('UrnBall_T1', '0008_auto_20220316_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bin10_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin10_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin1_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin1_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin2_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin2_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin3_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin3_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin4_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin4_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin5_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin5_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin6_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin6_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin7_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin7_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin8_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin8_teammate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin9_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin9_teammate',
        ),
        migrations.AddField(
            model_name='player',
            name='lucky_num',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team_prod',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
