# Generated by Django 2.2.12 on 2022-03-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrnBall_T1', '0009_auto_20220326_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='drawnG',
        ),
        migrations.RemoveField(
            model_name='player',
            name='drawnG_urn1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='drawnG_urn2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pointsPerG_urn1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pointsPerG_urn2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points_urn1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points_urn2',
        ),
    ]
