# Generated by Django 2.2.12 on 2021-09-29 00:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_redballs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num_redballs_urn1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num_redballs_urn2',
        ),
        migrations.AddField(
            model_name='player',
            name='num_Gballs',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_Gballs_urn1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_Gballs_urn2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
