# Generated by Django 2.2.12 on 2021-09-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0002_auto_20210928_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_round_number',
        ),
    ]
