# Generated by Django 2.2.12 on 2021-05-04 02:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0002_player_draw_urn2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_lotterytickets',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
