# Generated by Django 2.2.12 on 2021-05-04 02:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0003_auto_20210503_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_lotterytickets',
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded_Urn1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded_Urn2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs_urn1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs_urn2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
