# Generated by Django 2.2.12 on 2021-05-04 19:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0004_auto_20210503_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_round',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
