# Generated by Django 2.2.12 on 2021-05-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0005_player_game_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_round',
        ),
    ]
