# Generated by Django 2.2.12 on 2021-05-04 19:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0006_remove_player_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_round_number',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
