# Generated by Django 2.2.12 on 2021-05-04 21:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0007_player_game_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='check_slider_one',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
