# Generated by Django 2.2.12 on 2021-05-04 21:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0008_player_check_slider_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='check_slider_one',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
