# Generated by Django 2.2.12 on 2021-05-04 21:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0009_auto_20210504_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='check_slider_one',
        ),
        migrations.AddField(
            model_name='player',
            name='check_DecisionSlider',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
