# Generated by Django 2.2.12 on 2021-05-04 21:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0010_auto_20210504_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='check_DecisionSlider',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
