# Generated by Django 2.2.12 on 2021-08-10 22:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0011_auto_20210504_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='practice_guess_mine',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='practice_guess_teammate',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
