# Generated by Django 2.2.12 on 2021-08-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T1', '0013_auto_20210812_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='practice_guess_mine',
        ),
        migrations.RemoveField(
            model_name='player',
            name='practice_guess_teammate',
        ),
    ]
