# Generated by Django 2.2.12 on 2021-09-24 19:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part1_cq1',
            field=otree.db.models.StringField(choices=[('True', 'True'), ('False', 'False')], max_length=10000, null=True),
        ),
    ]
