# Generated by Django 2.2.12 on 2021-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff_slider',
        ),
    ]
