# Generated by Django 2.2.12 on 2021-05-06 19:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0002_remove_player_payoff_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='productivity',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
