# Generated by Django 2.2.12 on 2021-10-19 23:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0002_auto_20210924_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='GreenReceived',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
