# Generated by Django 2.2.12 on 2021-05-06 19:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0003_player_productivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fundamental',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
