# Generated by Django 2.2.12 on 2021-10-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0003_player_greenreceived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GreenReceived',
        ),
    ]
