# Generated by Django 2.2.12 on 2021-05-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0004_player_fundamental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fundamental',
        ),
    ]
