# Generated by Django 2.2.12 on 2021-10-20 10:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0004_remove_player_greenreceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part1_cq1',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
    ]
