# Generated by Django 2.2.12 on 2022-02-09 20:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0005_auto_20211020_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Ngreenball',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
