# Generated by Django 2.2.12 on 2022-02-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part1', '0006_player_ngreenball'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='part1_cq1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part1_cq2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='part1_cq3',
        ),
    ]
