# Generated by Django 2.2.12 on 2021-05-05 01:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='check_DecisionSlider',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_round_number',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded_Urn1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_LTs_Awareded_Urn2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs_urn1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_redballs_urn2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='part3_cq3',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='part3_cq4',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='part3_cq5',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
    ]
