# Generated by Django 2.2.12 on 2021-08-12 17:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T2', '0002_auto_20210504_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part3_cq1_a',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='part3_cq1_b',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
    ]
