# Generated by Django 2.2.12 on 2021-10-01 00:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3_T2', '0002_auto_20210930_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='num_LTs_Awareded',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='num_LTs_Awareded_Urn1',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='num_LTs_Awareded_Urn2',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
