# Generated by Django 2.2.12 on 2021-05-05 03:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part6', '0003_auto_20210504_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ambig1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'A'], [2, 'B']], null=True, verbose_name=''),
        ),
    ]
