# Generated by Django 2.2.12 on 2021-05-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part6', '0005_auto_20210504_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='like',
        ),
        migrations.RemoveField(
            model_name='player',
            name='payoff_slider',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sex',
        ),
    ]
