# Generated by Django 2.2.12 on 2021-05-06 02:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part6', '0006_auto_20210505_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ambig1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig11',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig12',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig13',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig14',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig15',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig16',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig17',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig18',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig19',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig20',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig9',
        ),
        migrations.AddField(
            model_name='player',
            name='ambig',
            field=otree.db.models.PositiveIntegerField(choices=[[1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, ''], [10, ''], [11, ''], [12, ''], [13, ''], [14, ''], [15, ''], [16, ''], [17, ''], [18, ''], [19, ''], [20, '']], null=True),
        ),
    ]
