# Generated by Django 2.2.12 on 2021-05-06 03:03

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part6', '0007_auto_20210505_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ambig',
            field=otree.db.models.PositiveIntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, ''], [10, ''], [11, ''], [12, ''], [13, ''], [14, ''], [15, ''], [16, ''], [17, ''], [18, ''], [19, '']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='practice',
            field=otree.db.models.PositiveIntegerField(blank=True, choices=[[1, ''], [2, '']], null=True),
        ),
    ]
