# Generated by Django 2.2.12 on 2022-02-27 03:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitSurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='major',
            field=otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Decline to state', 'Decline to state')], max_length=10000, null=True),
        ),
    ]
