# Generated by Django 2.2.12 on 2022-02-27 03:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitSurvey', '0002_player_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='major',
            field=otree.db.models.StringField(choices=[('Business/ Economics', 'Business/ Economics'), ('Engineering/ Computer Science', 'Engineering/ Computer Science'), ('Natural Science/ Mathmatics', 'Natural Science/ Mathmatics'), ('Humanities/ Social Science', 'Humanities/ Social Science')], max_length=10000, null=True),
        ),
    ]
