# Generated by Django 2.2.12 on 2022-02-27 04:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitSurvey', '0004_auto_20220226_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='advice',
            field=otree.db.models.LongStringField(null=True, verbose_name='Your comment here:'),
        ),
    ]
