# Generated by Django 2.2.12 on 2022-02-27 04:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitSurvey', '0005_auto_20220226_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='major',
            field=otree.db.models.StringField(choices=[('Yes.', 'Yes.'), ('No.', 'No.')], max_length=10000, null=True),
        ),
    ]
