# Generated by Django 2.2.12 on 2022-03-17 05:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitSurvey', '0006_auto_20220226_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='part1',
            field=otree.db.models.StringField(choices=[('Very easy', 'Very easy'), ('Easy', 'Easy'), ('Hard', 'Hard'), ('Very hard', 'Very hard')], max_length=10000, null=True),
        ),
    ]
