# Generated by Django 2.2.12 on 2021-10-20 09:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='GreenReceived',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
