# Generated by Django 2.2.12 on 2021-04-28 21:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_cq1',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='part2_cq3',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'True'], [1, 'False']], null=True),
        ),
    ]
