# Generated by Django 2.2.12 on 2021-05-06 20:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part2', '0002_auto_20210428_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fundamental',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
