# Generated by Django 2.2.12 on 2022-02-10 01:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part2', '0003_auto_20220209_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GreenReceived',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fundamental',
        ),
        migrations.AddField(
            model_name='player',
            name='own_ability',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='teammate_ability',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
