# Generated by Django 2.2.12 on 2021-04-28 04:20

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Part3_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part3_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Part3_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('part3_cq1_a', otree.db.models.IntegerField(null=True)),
                ('part3_cq1_b', otree.db.models.IntegerField(null=True)),
                ('part3_cq2_a', otree.db.models.IntegerField(null=True)),
                ('part3_cq2_b', otree.db.models.IntegerField(null=True)),
                ('part3_cq3', otree.db.models.StringField(choices=[('True', 'True'), ('False', 'False')], max_length=10000, null=True)),
                ('part3_cq4', otree.db.models.StringField(choices=[('True', 'True'), ('False', 'False')], max_length=10000, null=True)),
                ('part3_cq5', otree.db.models.StringField(choices=[('True', 'True'), ('False', 'False')], max_length=10000, null=True)),
                ('guess_mine', otree.db.models.IntegerField(null=True)),
                ('guess_teammate', otree.db.models.IntegerField(null=True)),
                ('draw_urn1', otree.db.models.IntegerField(null=True)),
                ('draw_urn2', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Part3.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Part3.Subsession')),
            ],
            options={
                'db_table': 'Part3_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Part3.Subsession'),
        ),
    ]
