# Generated by Django 2.2.12 on 2021-04-29 22:03

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='RecommendedAction',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
