# Generated by Django 2.2.12 on 2021-04-30 00:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part3', '0002_player_recommendedaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='RecommendedAction',
        ),
        migrations.AddField(
            model_name='player',
            name='RecommendedAction1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RecommendedAction2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
