# Generated by Django 2.2.12 on 2021-04-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part3', '0003_auto_20210429_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='RecommendedAction1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RecommendedAction2',
        ),
    ]
