# Generated by Django 2.2.12 on 2021-04-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part3', '0004_auto_20210429_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='draw_urn2',
        ),
    ]
