# Generated by Django 2.2.12 on 2021-09-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='practice',
        ),
    ]
