# Generated by Django 2.2.12 on 2021-05-05 02:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='risk',
            field=otree.db.models.PositiveIntegerField(blank=True, choices=[[1, 'A'], [2, 'B']], null=True),
        ),
    ]
