# Generated by Django 2.2.12 on 2021-05-05 02:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0002_auto_20210504_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='risk',
        ),
        migrations.AddField(
            model_name='player',
            name='practice',
            field=otree.db.models.PositiveIntegerField(blank=True, choices=[[1, 'A'], [2, 'B']], null=True),
        ),
    ]
