# Generated by Django 2.2.12 on 2021-05-05 23:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0003_auto_20210504_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ambig1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ambig9',
        ),
        migrations.RemoveField(
            model_name='player',
            name='payoff_slider',
        ),
        migrations.AddField(
            model_name='player',
            name='points_earned_Part5',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
