# Generated by Django 2.2.12 on 2021-05-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0004_auto_20210505_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='like',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sex',
        ),
    ]
