# Generated by Django 2.2.12 on 2021-05-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0005_auto_20210505_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='points_earned_Part5',
        ),
    ]
