# Generated by Django 2.2.12 on 2021-05-06 03:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Part5', '0006_remove_player_points_earned_part5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='risk1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='risk9',
        ),
        migrations.AddField(
            model_name='player',
            name='risk',
            field=otree.db.models.PositiveIntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='practice',
            field=otree.db.models.PositiveIntegerField(blank=True, choices=[[1, ''], [2, '']], null=True),
        ),
    ]
