# Generated by Django 2.2.12 on 2022-04-02 15:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aSliderTask', '0002_player_my_percentile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_percentile',
        ),
        migrations.AddField(
            model_name='player',
            name='pct',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='roundup_pct',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
