# Generated by Django 2.2.12 on 2022-04-02 16:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aSliderTask', '0003_auto_20220402_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_prod',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
