# Generated by Django 2.2.12 on 2022-04-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aSliderTask', '0004_player_my_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_prod',
        ),
    ]
