# Generated by Django 2.2.12 on 2022-04-02 21:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aSliderTask', '0005_remove_player_my_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='StateSpace',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='simple',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
